#!/bin/bash
printf '%\n' $(( $((5#$(echo $STIR | tr 'stir.' '01234'))) + $((5$#(echo $WATER | tr 'water' '01234'))) )) | tr '01234567' 'bestchol'



*By now typing the answer into the script shouldn't be a problem... That's if you copy correctly*


